include:
  - board: promicro_nrf52840
    shield: chunkeyb_left
    snippet: studio-rpc-usb-uart
  - board: promicro_nrf52840
    shield: chunkeyb_right
  - board: promicro_nrf52840
    shield: settings_reset
